name: tests

on:
  workflow_call

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-inf
  cancel-in-progress: true

jobs:
  build:
    
    runs-on: ubuntu-latest
        
    defaults:
      run:
        shell: bash
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load environment variables
        run: cat /root/actions-runner-config/.env >> $GITHUB_ENV 

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./tests/requirements.txt

      - name: Start tests
        run: |
          bash -c "./tests/run-tests.sh"
