name: PR

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/**'
      - 'docker/**'
      - 'dev/docker/**'
      - 'llm_on_ray/common/**'
      - 'llm_on_ray/finetune/**'
      - 'llm_on_ray/inference/**'
      - 'llm_on_ray/rlhf/**'
      - 'tools/**'
      - 'pyproject.toml'
      - 'tests/**'

jobs:

  Lint:
    uses: ./.github/workflows/workflow_lint.yml

  Tests:
    needs: Lint
    uses: ./.github/workflows/workflow_tests.yml

  call-getting-started:
    needs: [call-lint, call-tests]
    uses: ./.github/workflows/workflow_getting_started.yml

  Inference:
    needs: Lint
    uses: ./.github/workflows/workflow_inference.yml

  Finetune:
    needs: Lint
    uses: ./.github/workflows/workflow_finetune.yml
