name: Merge

on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'docker/**'
      - 'dev/docker/**'
      - 'llm_on_ray/common/**'
      - 'llm_on_ray/finetune/**'
      - 'llm_on_ray/inference/**'
      - 'llm_on_ray/rlhf/**'
      - 'tools/**'
      - 'pyproject.toml'
      - 'tests/**'

jobs:
  call-lint:
    uses: ./.github/workflows/workflow_lint.yml

  call-getting-started:
    needs: call-lint
    uses: ./.github/workflows/workflow_getting_started.yml

  Tests:
    needs: call-lint
    uses: ./.github/workflows/workflow_tests.yml

  Inference:
    needs: call-lint
    uses: ./.github/workflows/workflow_inference.yml

  Finetune:
    needs: call-lint
    uses: ./.github/workflows/workflow_finetune.yml
